services:
  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    container_name: medusa_backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - ../../apps/backend/.env
    volumes:
      - ../../apps/backend:/server
      - /server/node_modules
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge
